#
# Expected repository setup
#
# 1. Pages is enabled and tracking a branch that does not contain anything
# 2. The `github-pages` environment has been created and is protected (either via the "Selected branches" or "Protected branches" options)
# 3. The repository is an actor on this feature flag: https://admin.github.com/devtools/feature_flags/pages_preview_deployments
#

on:
  push:
    branches:
      - main

# Required: Pages permissions
permissions:
  contents: read
  pages: write
  id-token: write

name: Build & Deploy Pages Production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      #
      # Required: Checkout (current branch)
      #
      - name: Checkout
        uses: actions/checkout@v2

      #
      # Your build steps (for you to customize)
      # A Gatsby example is provided here.
      #

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      #
      # Required: Pages artifacts creation
      #

      - name: Archive build output
        run: "tar --dereference --directory public/ -cvf artifact.tar ."

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: artifact.tar

  #
  # Required: Deployment of the artifacts to production
  #

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: paper-spa/deploy-pages@main
        # with:
        #   preview: 'false'
